apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "toleration-webhook.fullname" . }}
  labels:
    {{- include "toleration-webhook.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/allow-direct-injection: "true"
spec:
  dnsNames:
  - {{ include "toleration-webhook.fullname" . }}.{{ .Release.Namespace }}.svc
  - {{ include "toleration-webhook.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    group: cas-issuer.jetstack.io
    kind: GoogleCASClusterIssuer
    name: googlecasclusterissuer
  privateKey:
    rotationPolicy: Always
  renewBefore: 1080h0m0s
  secretName: {{ include "toleration-webhook.fullname" . }}
