apiVersion: v1
kind: Service
metadata:
  name: {{ include "toleration-webhook.fullname" . }}
  labels:
    {{- include "toleration-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
    - name: http-monitoring
      port: {{ .Values.service.monitoringPort }}
      protocol: TCP
      targetPort: http-monitoring
  selector:
    {{- include "toleration-webhook.selectorLabels" . | nindent 4 }}
